 
substitutions:
  device_name: electriq-12000-ac-01
  climate_id: electriq_12000_ac_01
  friendly_name: "Electriq 12000 AC 01"

external_components:
  - source: github://dslatford/electriq_ac
    components: [ electriq_ac ]

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0  # Disable logging over UART since we're using it for the AC

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

# Configure UART for communication with AC unit
uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600

# Configure the climate platform
climate:
  - platform: electriq_ac
    name: "${friendly_name}"
    id: "${climate_id}

# Optional: Fan overrun automation to prevent temperature overshooting in heat mode
# This runs the fan after heating stops to remove latent heat from the evaporator
binary_sensor:
  - platform: template
    id: fan_overrun
    lambda: |-
      if (id(${climate_id}).action == CLIMATE_ACTION_IDLE && 
          id(${climate_id}).mode == CLIMATE_MODE_HEAT) {
        return true;
      }
      return false;
    on_press:
      then:
        - logger.log: "Heating stopped, starting fan overrun"
        - delay: 90s
        - climate.control:
            id: ${climate_id}
            fan_mode: HIGH
        - delay: 60s
        - climate.control:
            id: ${climate_id}
            fan_mode: LOW
